default:
  tags:
    - runner_CRIM

test-job1:
  stage: test
  script:
    - echo "This job tests something"

build-job:
  stage: build
  variables:
    DOCKER_IMAGE: "$DOCKER_REGISTRY_URL/ccdp_task_runner"
  script:
    - echo "Starting Docker"
    - docker build -f dockerfiles/build/task-runner/Dockerfile -t $DOCKER_IMAGE .
    - docker image tag $DOCKER_IMAGE $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push -a $DOCKER_IMAGE
    - echo "Done !"
