version: "3.8"

name: climatedata-docker

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        EXTRA_WP_PLUGINS_DIR: ./res/wp-plugins
        EXTRA_VENDOR_ASSETS_DIR: ./res/vendor
        RUNNER_IMAGE: climatedata-runner
    ports:
      - 80:80
      - 443:443
    image: climatedata-www
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./res/logs/apache
        target: /var/log/apache2
      - type: bind
        source: ./res/logs/php
        target: /var/log/php
      - type: bind
        source: dockerfiles/www/configs/php/php-development.ini
        target: /usr/local/etc/php/php.ini
#      - type: bind
#        source: ./res/ssl
#        target: /etc/ssl/certs
    environment:
      WP_DB_HOST: db
      WP_DB_NAME: climatedata
      WP_DB_USER: climatedata
      WP_DB_PASSWORD: climatedata
      WP_WP_DEBUG: "true"
      WP_WP_MEMORY_LIMIT: 128M
      WP_AUTH_KEY: "]jkQVSgz &&!>1<bK9JpD<Y_3 Xb#t|4=(g|Km+._e{YC5Bb>zrJl8I[r)$$Qq%{"
      WP_SECURE_AUTH_KEY: "/{LmO@Hj|=6|y>W|9%uEPIvd%@F,?@tOofJo6C:YnOdfQk@t-K!4n,3Kolvo fDy"
      WP_LOGGED_IN_KEY:  "K!9E9_~C;6Fqh8/i>^dWK7~F=mk$FsWOyz^y^A-0eU_a&d-ysykH9/1:/ils,F1d"
      WP_NONCE_KEY:  "azzh.48v*8iRO2l`*-=gUT_kYOD<Ig9[qUaM>phg6ip8-avN<`#TBYf?yDPL_5UO"
      WP_AUTH_SALT: "{i{+<`BhmtR`I2+9]lE2IU3!ypRkw9HjY;1}L!/OndY9nHR%N1*^W2?!?+cPG0+c"
      WP_SECURE_AUTH_SALT: "wI~I>Rooz-+-{lNI%[g3~|# 9R4 k6I?j7vF!$${Q>I^Utr^Pr5tZuZg?Pc$+N5gF"
      WP_LOGGED_IN_SALT:  "i=GdI3/$VdU,+Y T-f?kr-.0(Q4kxiqZ[Hu*tB3TY(@W5M3mee/XRI-~[cHNOZ&j"
      WP_NONCE_SALT:  "Up<Q /#k4>;p)GYi)+--Pls<>-7NywT.JVmrW9C,bET(F@Tz*Bkp+kHtN)87<5 l"
      APP_NO_HTTPS: "true"
    
  db:
    #image: mariadb:10.5
    image: registry.gitlab.com/crim.ca/clients/ccdp/docker/db:v2
    volumes:
      # - db_data:/var/lib/mysql
      - db_data_v2:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: climatedata
      MARIADB_USER: climatedata
      MARIADB_PASSWORD: climatedata
    command: --innodb-buffer-pool-size=128M --innodb-log-buffer-size=64M --innodb-doublewrite=0 --innodb-flush-log-at-trx-commit=0
    
volumes:
  db_data: {}
  db_data_v2: {}