# syntax=docker/dockerfile:1

# Dockerfile for the climatedata.ca web server.
#
# The image contains PHP-FPM, a web server (Apache) and all the site files (WordPress, plugins, custom themes).
#
# This image doesn't contain:
# - The database (should be another Docker image).
# - The "upload/" directory containing files uploaded from the administration (should be mounted as a volume since we
#     need those files to persist).
#
# Build arguments:
#  - TASK_RUNNER_IMAGE (required): name of the task runner Docker image (see description below).
#  - EXTRA_WP_PLUGINS_DIR (optional): directory, in the build context, containing zip files of extra WordPress plugins
#      to extract in the assets/plugins/ directory. Can be used, for example, to add plugins not available in the
#      WordPress' plugin directory.
#  - EXTRA_VENDOR_ASSETS_DIR (optional): directory, in the build context, containing zip files to extract in the
#      assets/vendor/ directory.
#
# Special runtime environment variables (used only when running the container):
#  - WP_*: variables prefixed with WP_ are used to set WordPress constants. For example `WP_DB_NAME=test` will set the
#      `DB_NAME` WordPress constant to "test". See dockerfiles/www/configs/wordpress/wp-config.php for details.
#  - APP_NO_HTTPS: if "true", informs various components in the container to allow non-HTTPS requests. If not set, or
#      not set to "true", those components will act in "required HTTPS" mode.
#
# The build process is multi-stage, and the "target" you want to build the website is "production".
#
# The build process is two-step:
#   1) Some static assets (ex: CSS files) are built from source files (ex: SCSS). This process is done by a
#      "task runner" image that generates those files locally. You must supply the name of the task runner Docker image
#      with the `TASK_RUNNER_IMAGE` build argument. See the `dockerfiles/runner/Dockerfile` file to build the
#      task runner image.
#   2) The production web server is built. It contains PHP-FPM, Apache, WordPress, the required WordPress plugins, and
#      all the site's files, including the files generated by the task runner and the custom themes.
#
# Example build:
#
#   `docker build --target production --build-arg TASK_RUNNER_IMAGE=task-runner:v2`

ARG TASK_RUNNER_IMAGE

###
# Task runner stage.
#
# The task runner compiles some site's assets from their source files. It outputs the generated files in a local dist/
# directory.
###
FROM ${TASK_RUNNER_IMAGE} as task-runner

WORKDIR /home/node/app

COPY --chown=node framework src/framework
COPY --chown=node fw-child src/fw-child

RUN compile-sass.sh src dist

CMD ["echo", "Done"]


###
# Production website building stage.
###
FROM php:8.2-fpm as production

RUN apt-get update && apt-get install -y --no-install-recommends \
        apache2 \
        jq \
        less \
        libapache2-mod-fcgid \
        supervisor \
        unzip \
        vim \
        zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# WP-CLI download and installation

WORKDIR /usr/local/bin
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && mv wp-cli.phar wp \
    && chmod +x wp

# Supervisord configuration

COPY dockerfiles/www/configs/supervisor/supervisord.conf /etc/

# Apache configuration. Enable modules and the main website's configurations (HTTP and HTTPS).

RUN a2enmod actions fcgid alias proxy proxy_fcgi setenvif rewrite ssl

COPY dockerfiles/www/configs/apache/100-climatedata*.conf /etc/apache2/sites-available
COPY dockerfiles/www/configs/apache/php-fpm.conf /etc/apache2/conf-available

RUN a2dissite 000-default && \
    a2ensite 100-climatedata && \
    a2ensite 100-climatedata-ssl && \
    a2enconf php-fpm

RUN rm /var/www/html/index.html

# PHP: Enabling extensions and configuration (php.ini)

# https://github.com/mlocati/docker-php-extension-installer
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions \
    gd \
    mysqli \
    pdo \
    pdo_mysql \
    zip

COPY --chmod=755 dockerfiles/www/bin /usr/local/bin

COPY --chmod=644 dockerfiles/www/configs/php/php.ini /usr/local/etc/php
RUN mkdir /var/log/php && chown www-data:www-data /var/log/php

# Wordpress files installation and configuration

USER www-data
WORKDIR /var/www/html/site

RUN wp core download --version=6.3.1 --skip-content
RUN mv wp-content assets
RUN echo "<?php define('WP_USE_THEMES', true); require( dirname( __FILE__ ) . '/site/wp-blog-header.php' );" > ../index.php

COPY --chown=www-data:www-data --chmod=744 dockerfiles/www/configs/wordpress/wp-config.php .
COPY --chown=www-data:www-data --chmod=744 dockerfiles/www/configs/wordpress/.htaccess /var/www/html

WORKDIR /var/www/html/site/assets/vendor

ARG EXTRA_VENDOR_ASSETS_DIR
RUN --mount=type=bind,target=/tmp/vendor-assets,source=$EXTRA_VENDOR_ASSETS_DIR unzip-all.sh /tmp/vendor-assets

# WordPress plugins installation

WORKDIR /var/www/html/site/assets/plugins

ARG EXTRA_WP_PLUGINS_DIR
RUN --mount=type=bind,target=/tmp/wp-plugins,source=$EXTRA_WP_PLUGINS_DIR unzip-all.sh /tmp/wp-plugins

RUN download-wp-plugin.sh \
        classic-editor=1.6.3 \
        custom-taxonomy-order-ne=4.0.0 \
        post-type-switcher=3.3.0 \
        regenerate-thumbnails=3.1.6 \
        simple-page-ordering=2.5.1 \
        wordpress-importer=0.8.1

# Site's custom WordPress themes installation

WORKDIR /var/www/html/site/assets/themes

COPY --chown=www-data:www-data --from=task-runner /home/node/app/dist .

COPY --chown=www-data:www-data framework framework
COPY --chown=www-data:www-data fw-child fw-child

WORKDIR /root
USER root
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
